---
- name: Install Apache Tomcat9 using ansible
  become: true
  hosts: all
  tasks: 
    - name: Create tomcat Group
      group:
        name: tomcat 
        state: present
 
    - name: Create tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /usr/share/tomcat
        createhome: no
        system: yes
        state: present
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 750
        recurse: yes
 
    - name: Download & unarchive tomcat9
      unarchive:
        src: https://nexus.chubbdigital.com/repository/application-platform-support-hosted/tomcat/apache-tomcat-9.0.59.tar.gz
        dest: /opt/tomcat9
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 750
        recurse: yes
        state: directory
 
    - name: Copy Tomcat service from local to remote
      copy:
        src: playbooks/tomcat/tomcat9.service.rhel8
        dest: /etc/systemd/system/tomcat9.service
        mode: 0755
 
    - name: Start and Enable tomcat9 on sever
      systemd:
        name: tomcat9
        state: started
        daemon_reload: true
